// Auto-generated data module for ORBIT

export const SUBJECTS = ["Mathematics","Physics","Chemistry","Biology","Computer Science","Economics","Business","Accounting","Psychology","English","Art & Design","Geography","Environmental Science"];
export const INTERESTS = ["AI","Technology","Space","Design","Business","Health","Science","Environment","Psychology","Finance","Creativity","Engineering"];
export const STRENGTHS = ["Problem Solving","Communication","Creativity","Leadership","Analysis","Research","Programming","Visual Thinking","Teamwork","Critical Thinking"];

export const SUBJECTS_AR = {"Mathematics":"الرياضيات","Physics":"الفيزياء","Chemistry":"الكيمياء","Biology":"الأحياء","Computer Science":"علوم الحاسوب","Economics":"الاقتصاد","Business":"إدارة الأعمال","Accounting":"المحاسبة","Psychology":"علم النفس","English":"اللغة الإنجليزية","Art & Design":"الفن والتصميم","Geography":"الجغرافيا","Environmental Science":"علوم البيئة"};
export const INTERESTS_AR = {"AI":"الذكاء الاصطناعي","Technology":"التكنولوجيا","Space":"الفضاء","Design":"التصميم","Business":"الأعمال","Health":"الصحة","Science":"العلوم","Environment":"البيئة","Psychology":"علم النفس","Finance":"التمويل","Creativity":"الإبداع","Engineering":"الهندسة"};
export const STRENGTHS_AR = {"Problem Solving":"حل المشكلات","Communication":"التواصل","Creativity":"الإبداع","Leadership":"القيادة","Analysis":"التحليل","Research":"البحث","Programming":"البرمجة","Visual Thinking":"التفكير البصري","Teamwork":"العمل الجماعي","Critical Thinking":"التفكير النقدي"};

export const CAREERS = [
 {id:"environmental-science",category:"Environment",categoryAr:"البيئة",title:"Environmental Science",titleAr:"علوم البيئة",desc:"Understanding and protecting the natural world — science for a sustainable future.",descAr:"فهم العالم الطبيعي وحمايته — علم من أجل مستقبل مستدام.",subjects:["Environmental Science","Geography","Biology"],interests:["Environment","Science"],strengths:["Research","Analysis"],degrees:["BSc Environmental Science","BSc Sustainability"]},
 {id:"biomedical-engineering",category:"Engineering",categoryAr:"الهندسة",title:"Biomedical Engineering",titleAr:"الهندسة الطبية الحيوية",desc:"Where engineering meets the human body — technology that improves and saves lives.",descAr:"حيث تلتقي الهندسة بجسم الإنسان — تقنية تحسّن الحياة وتنقذها.",subjects:["Biology","Chemistry","Physics"],interests:["Health","Science","Engineering"],strengths:["Problem Solving","Research"],degrees:["BSc Biomedical Engineering"]},
 {id:"international-relations",category:"Social Sciences",categoryAr:"العلوم الاجتماعية",title:"International Relations",titleAr:"العلاقات الدولية",desc:"How nations, economies, and people interact on the global stage.",descAr:"كيف تتفاعل الدول والاقتصادات والشعوب على المسرح العالمي.",subjects:["Economics","Geography","English"],interests:["Business","Psychology"],strengths:["Communication","Critical Thinking"],degrees:["BA International Relations","BA Political Science"]},
 {id:"medicine",category:"Healthcare",categoryAr:"الرعاية الصحية",title:"Medicine",titleAr:"الطب",desc:"The science and art of healing — diagnosing, treating, and caring for people.",descAr:"علم وفن الشفاء — التشخيص والعلاج ورعاية الناس.",subjects:["Biology","Chemistry"],interests:["Health","Science"],strengths:["Research","Critical Thinking"],degrees:["MBBS Medicine","BSc Pre-Med"]},
 {id:"psychology",category:"Social Sciences",categoryAr:"العلوم الاجتماعية",title:"Psychology",titleAr:"علم النفس",desc:"The science of the mind and behavior — understanding how people think and feel.",descAr:"علم العقل والسلوك — فهم كيف يفكر الناس ويشعرون.",subjects:["Psychology","Biology"],interests:["Psychology","Health"],strengths:["Communication","Research"],degrees:["BSc Psychology","BA Behavioral Science"]},
 {id:"business-analytics",category:"Business",categoryAr:"الأعمال",title:"Business Analytics",titleAr:"تحليلات الأعمال",desc:"Data-driven decision making for organizations — where numbers meet strategy.",descAr:"اتخاذ قرارات قائمة على البيانات للمؤسسات — حيث تلتقي الأرقام بالاستراتيجية.",subjects:["Economics","Mathematics","Business"],interests:["Business","Finance"],strengths:["Analysis","Problem Solving"],degrees:["BSc Business Analytics","BBA"]},
 {id:"fintech-finance",category:"Business",categoryAr:"الأعمال",title:"FinTech & Finance",titleAr:"التكنولوجيا المالية والتمويل",desc:"Reinventing money and markets with technology and financial insight.",descAr:"إعادة ابتكار المال والأسواق بالتكنولوجيا والفهم المالي.",subjects:["Economics","Mathematics"],interests:["Finance","Business","Technology"],strengths:["Analysis","Critical Thinking"],degrees:["BSc Finance","BSc FinTech"]},
 {id:"aerospace-engineering",category:"Engineering",categoryAr:"الهندسة",title:"Aerospace Engineering",titleAr:"هندسة الطيران والفضاء",desc:"Designing the machines that leave the ground — aircraft, rockets, and beyond.",descAr:"تصميم الآلات التي تغادر الأرض — الطائرات والصواريخ وما بعدها.",subjects:["Mathematics","Physics"],interests:["Space","Engineering"],strengths:["Problem Solving","Analysis"],degrees:["BEng Aerospace Engineering"]},
 {id:"artificial-intelligence",category:"Technology",categoryAr:"التكنولوجيا",title:"Artificial Intelligence",titleAr:"الذكاء الاصطناعي",desc:"Building systems that learn, reason and adapt — the frontier of computing.",descAr:"بناء أنظمة تتعلم وتفكر وتتكيف — أحدث ما توصلت إليه الحوسبة.",subjects:["Mathematics","Computer Science"],interests:["AI","Technology"],strengths:["Programming","Analysis"],degrees:["BSc Artificial Intelligence","BSc Computer Science (AI)"]},
 {id:"robotics-engineering",category:"Engineering",categoryAr:"الهندسة",title:"Robotics Engineering",titleAr:"هندسة الروبوتات",desc:"Combining mechanics, electronics and code to build machines that act in the world.",descAr:"دمج الميكانيكا والإلكترونيات والبرمجة لبناء آلات تتفاعل مع العالم.",subjects:["Mathematics","Physics","Computer Science"],interests:["Technology","Engineering"],strengths:["Programming","Problem Solving"],degrees:["BEng Robotics","BSc Mechatronics"]},
 {id:"data-science",category:"Technology",categoryAr:"التكنولوجيا",title:"Data Science",titleAr:"علم البيانات",desc:"Turning raw data into insight — the discipline behind modern decision-making.",descAr:"تحويل البيانات الخام إلى رؤى — التخصص وراء اتخاذ القرار الحديث.",subjects:["Mathematics","Computer Science"],interests:["AI","Technology","Business"],strengths:["Analysis","Programming"],degrees:["BSc Data Science"]},
 {id:"cybersecurity",category:"Technology",categoryAr:"التكنولوجيا",title:"Cybersecurity",titleAr:"الأمن السيبراني",desc:"Defending systems, data and people from digital threats.",descAr:"حماية الأنظمة والبيانات والأشخاص من التهديدات الرقمية.",subjects:["Computer Science","Mathematics"],interests:["Technology"],strengths:["Analysis","Problem Solving","Programming"],degrees:["BSc Cybersecurity"]},
 {id:"ux-design",category:"Design",categoryAr:"التصميم",title:"UX Design",titleAr:"تصميم تجربة المستخدم",desc:"Shaping how people experience technology — clarity, empathy and craft.",descAr:"تشكيل كيفية تفاعل الناس مع التكنولوجيا — الوضوح والتعاطف والحرفية.",subjects:["Art & Design","Psychology"],interests:["Design","Creativity"],strengths:["Visual Thinking","Creativity"],degrees:["BA UX Design","BSc Human-Computer Interaction"]},
 {id:"product-design",category:"Design",categoryAr:"التصميم",title:"Product Design",titleAr:"تصميم المنتجات",desc:"Designing the products people use every day, from concept to launch.",descAr:"تصميم المنتجات التي يستخدمها الناس يوميًا، من الفكرة إلى الإطلاق.",subjects:["Art & Design","Psychology","Business"],interests:["Design","Business"],strengths:["Visual Thinking","Creativity","Leadership"],degrees:["BA Product Design"]},
 {id:"computer-science",category:"Technology",categoryAr:"التكنولوجيا",title:"Computer Science",titleAr:"علوم الحاسوب",desc:"The foundations of computing — algorithms, systems and software.",descAr:"أسس الحوسبة — الخوارزميات والأنظمة والبرمجيات.",subjects:["Computer Science","Mathematics"],interests:["Technology","AI"],strengths:["Programming","Problem Solving"],degrees:["BSc Computer Science"]},
 {id:"software-engineering",category:"Technology",categoryAr:"التكنولوجيا",title:"Software Engineering",titleAr:"هندسة البرمجيات",desc:"Building reliable software at scale — from idea to production.",descAr:"بناء برمجيات موثوقة على نطاق واسع — من الفكرة إلى الإنتاج.",subjects:["Computer Science"],interests:["Technology"],strengths:["Programming","Problem Solving"],degrees:["BEng Software Engineering"]},
 {id:"biotechnology",category:"Science",categoryAr:"العلوم",title:"Biotechnology",titleAr:"التقنية الحيوية",desc:"Using living systems to develop products that improve human life.",descAr:"استخدام الأنظمة الحية لتطوير منتجات تحسّن حياة الإنسان.",subjects:["Biology","Chemistry"],interests:["Science","Health"],strengths:["Research"],degrees:["BSc Biotechnology"]},
 {id:"interaction-design",category:"Design",categoryAr:"التصميم",title:"Interaction Design",titleAr:"تصميم التفاعل",desc:"Designing the moments where people and systems meet.",descAr:"تصميم اللحظات التي يلتقي فيها الناس بالأنظمة.",subjects:["Art & Design","Psychology"],interests:["Design"],strengths:["Visual Thinking"],degrees:["BA Interaction Design"]}
];

export const UNIVERSITIES = [
 {id:"khalifa",abbr:"KU",name:"Khalifa University",nameAr:"جامعة خليفة",aliases:["khalifa","khalifa university"],country:"UAE",city:"Abu Dhabi",group:"uae",degrees:["Engineering","Computer Science","Aerospace Engineering","Biomedical Engineering"],tuition:"AED 65,000–95,000 / yr",scholarship:"Merit-based scholarships available",budget:"high"},
 {id:"uaeu",abbr:"UAEU",name:"United Arab Emirates University",nameAr:"جامعة الإمارات العربية المتحدة",aliases:["uaeu","emirates university","united arab emirates university"],country:"UAE",city:"Al Ain",group:"uae",degrees:["Business","Medicine","Engineering","Education"],tuition:"AED 50,000–70,000 / yr",scholarship:"National merit scholarships available",budget:"medium"},
 {id:"sharjah",abbr:"Sharjah",name:"University of Sharjah",nameAr:"جامعة الشارقة",aliases:["sharjah","university of sharjah"],country:"UAE",city:"Sharjah",group:"uae",degrees:["Medicine","Business","Architecture","Pharmacy"],tuition:"AED 45,000–65,000 / yr",scholarship:"Need & merit based scholarships",budget:"medium"},
 {id:"aus",abbr:"AUS",name:"American University of Sharjah",nameAr:"الجامعة الأمريكية في الشارقة",aliases:["aus","american university of sharjah"],country:"UAE",city:"Sharjah",group:"uae",degrees:["Business Analytics","Engineering","Design","Computer Science"],tuition:"AED 75,000–100,000 / yr",scholarship:"Merit scholarships available",budget:"high"},
 {id:"rit",abbr:"RIT Dubai",name:"Rochester Institute of Technology Dubai",nameAr:"معهد روتشستر للتكنولوجيا دبي",aliases:["rit","rit dubai","rochester institute","rochester institute of technology dubai","rochester"],country:"UAE",city:"Dubai",group:"uae",degrees:["Computer Science","Data Science","Engineering","Design"],tuition:"AED 70,000–90,000 / yr",scholarship:"Merit scholarships available",budget:"high"},
 {id:"uwl",abbr:"UWL RAK",name:"University of West London — RAK Campus",nameAr:"جامعة غرب لندن — فرع رأس الخيمة",aliases:["uwl","uwl rak","west london","west london rak","rak","university of west london"],country:"UAE",city:"Ras Al Khaimah",group:"uae",degrees:["Business","Computing","Psychology"],tuition:"AED 40,000–55,000 / yr",scholarship:"Need-based scholarships available",budget:"low"},
 {id:"imperial",abbr:"Imperial",name:"Imperial College London",nameAr:"إمبريال كوليدج لندن",aliases:["imperial","imperial college london"],country:"UK",city:"London",group:"intl",degrees:["Engineering","Medicine","AI","Data Science"],tuition:"£35,000–45,000 / yr",scholarship:"Sample: select merit scholarships",budget:"high"},
 {id:"eth",abbr:"ETH Zürich",name:"ETH Zürich",nameAr:"المعهد الفيدرالي السويسري للتكنولوجيا زيورخ",aliases:["eth","eth zurich","eth zürich"],country:"Switzerland",city:"Zürich",group:"intl",degrees:["Engineering","Computer Science","Robotics"],tuition:"CHF 1,500–3,000 / yr",scholarship:"Sample: excellence scholarships",budget:"low"},
 {id:"toronto",abbr:"U of T",name:"University of Toronto",nameAr:"جامعة تورنتو",aliases:["toronto","university of toronto","u of t"],country:"Canada",city:"Toronto",group:"intl",degrees:["Business","Computer Science","International Relations"],tuition:"CAD 55,000–65,000 / yr",scholarship:"Sample: entrance scholarships",budget:"high"},
 {id:"tum",abbr:"TUM",name:"Technical University of Munich",nameAr:"جامعة ميونخ التقنية",aliases:["tum","technical university of munich","munich"],country:"Germany",city:"Munich",group:"intl",degrees:["Engineering","Robotics","Data Science"],tuition:"€150–3,000 / yr",scholarship:"Sample: DAAD-linked scholarships",budget:"low"},
 {id:"rwth",abbr:"RWTH",name:"RWTH Aachen University",nameAr:"جامعة آخن التقنية",aliases:["rwth","rwth aachen","aachen"],country:"Germany",city:"Aachen",group:"intl",degrees:["Engineering","Computer Science","Biomedical Engineering"],tuition:"€150–3,000 / yr",scholarship:"Sample: DAAD-linked scholarships",budget:"low"}
];

export const CATEGORY_UNI_MAP = {
  "Environment":["khalifa","uaeu","eth"],
  "Engineering":["khalifa","rit","eth","tum","rwth"],
  "Social Sciences":["toronto","aus","uwl"],
  "Healthcare":["sharjah","uaeu","imperial"],
  "Business":["aus","uwl","toronto"],
  "Technology":["rit","khalifa","eth","tum"],
  "Design":["rit","aus","uwl"],
  "Science":["khalifa","eth","rwth"]
};
/* ======================= i18n ======================= */
export const STR = {
en:{
 nav_home:"Home",nav_mypath:"My Path",nav_careers:"Careers",nav_constellation:"Constellation",nav_universities:"Universities",nav_whatif:"What If",nav_why:"Why",nav_saved:"Saved",nav_compare:"Compare",nav_pathways:"Pathways",nav_profile:"Profile",nav_features:"Features",
 hero_label:"ORBIT · POSSIBILITY ENGINE",
 hero_l1:"SEE WHERE",hero_l2:"YOUR CHOICES",hero_l3:"COULD TAKE YOU.",
 hero_sub:"Orbit connects your subjects, interests and strengths to careers, degrees and universities that could fit your future.",
 cta_build:"BUILD MY PATH", cta_explore_careers:"EXPLORE CAREERS",
 problem_home_h:"You know what you study. But do you know what it could become?",
 problem_1_l:"SUBJECTS",problem_1_d:"what you study",problem_2_l:"CAREERS",problem_2_d:"what it becomes",problem_3_l:"DEGREES",problem_3_d:"how you get there",problem_4_l:"UNIVERSITIES",problem_4_d:"where you go",
 closing_label:"05 — MULTIPLE FUTURES", closing_h1:"ONE CHOICE.", closing_h2:"MANY CONNECTIONS.", closing_h3:"MULTIPLE FUTURES.",
 possibility_h:"Watch possibilities shift.",
 possibility_p:"Remove a subject. Add another. The entire network rethinks itself — careers, degrees, universities. Decisions, not destiny.",
 cta_tryit:"TRY WHAT IF",
 uni_label:"04 — UNIVERSITY DESTINATIONS", uni_h:"Where your pathway could land.", explore_all:"Explore all",
 universe_h:"A universe of careers, organized around you.",
 universe_p:"Each career connects to others through shared subjects, skills and degrees. Explore the relationships. Find the one that fits.",
 open_constellation:"Open the constellation",
 mypath_empty_h:"Your path hasn't been built yet.",
 mypath_empty_p:"Tell Orbit what you study, what you're curious about, and what you're good at — then watch your possibilities appear.",
 back:"Back", cont:"Continue", generate:"Generate possibilities",
 step_subjects_h:"What do you study?", step_subjects_p:"Select the subjects you take. Each one becomes a signal.",
 step_interests_h:"What are you curious about?", step_interests_p:"Add the fields that pull your attention.",
 step_strengths_h:"What are you good at?", step_strengths_p:"Pick the strengths that feel most like you.",
 step_futures_h:"What kind of futures interest you?", step_futures_p:"Optional — shape the kinds of paths you want to see.",
 selected:"SELECTED", home_label:"Home", generating:"GENERATING POSSIBILITIES", building_space:"Building your possibility space…",
 mypath_h:"Your path", mypath_p:"Explore the possibilities that grow from your profile.", edit_profile:"Edit profile",
 subjects_l:"SUBJECTS", interests_l:"INTERESTS", strengths_l:"STRENGTHS", primary_pathway:"PRIMARY PATHWAY",
 top_matches:"Top career matches", view_all:"View all", recommended_dest:"Recommended destinations", relevant_degree:"Relevant degree",
 careers_h:"Careers", careers_p:"Explore where your subjects, interests and strengths could lead.",
 explore:"Explore", match:"MATCH", why_match:"Why this matches",
 constellation_h:"Constellation", constellation_p:"Hover to reveal relationships. Click a node to re-center the universe.",
 constellation_eyebrow:"CAREER CONSTELLATION",
 cl_label:"MAPPING YOUR UNIVERSE", cl_sub:"Connecting subjects, interests & strengths…",
 connected_careers:"CONNECTED CAREERS", open_career:"Open",
 universities_h:"Universities", universities_p:"Explore destinations in your pathway universe. Match scores reflect your profile.",
 search_uni:"Search universities... (try RIT, UWL, Khalifa, Imperial)",
 country_l:"COUNTRY", city_l:"CITY", degree_l:"DEGREE", budget_l:"BUDGET", all:"All", all_degrees:"All degrees",
 whatif_h:"What If", whatif_p:"Change your profile hypothetically and watch the possibility space respond — instantly.",
 tab_subjects:"Subjects", tab_interests:"Interests", tab_strengths:"Strengths",
 current_subjects:"CURRENT SUBJECTS", none_add:"None — add some below.", add_remove:"ADD / REMOVE",
 possibility_space:"POSSIBILITY SPACE · TOP CAREERS",
 pathway_gained:"PATHWAY GAINED", pathway_strengthened:"PATHWAY STRENGTHENED", pathway_reduced:"PATHWAY REDUCED", no_change:"No change.",
 reset_profile:"Reset to my profile", hypothetical_note:"The hypothetical profile stays separate from your real one. Reset restores it.",
 why_title:"Problem & Solution",
 why_eyebrow:"WHY ORBIT", why_hero_h1:"Decisions,", why_hero_h2:"not destiny.",
 why_hero_p:"ORBIT doesn't predict your future. It helps you see the possibilities your choices could open — and how changing one thing changes everything.",
 future_options_l:"FUTURE OPTIONS", future_options_d:"what becomes possible",
 principle_label:"THE PRINCIPLE",
 evidence_39:"of students across OECD countries are unclear about their career expectations.",
 evidence_21:"of students can be classified as career-misaligned — their education plans and career expectations don't match.",
 evidence_gap:"career misalignment among students from the least advantaged vs. most advantaged socioeconomic quarters — a 23 percentage-point gap.",
 src_39:"Source: OECD — The State of Global Teenage Career Preparation (20 May 2025)",
 src_21:"Source: OECD — Career uncertainty",
 src_gap:"Source: OECD — Challenging Social Inequality Through Career Guidance",
 misalignment_chart_title:"Career misalignment by socioeconomic background",
 misalignment_src:"Group · Percentage · 23pp gap between groups · Source: OECD, Challenging Social Inequality Through Career Guidance. These are OECD/PISA research findings about student populations, not a prediction about any individual.",
 least_advantaged:"Least advantaged", most_advantaged:"Most advantaged",
 landscape_label:"THE LANDSCAPE", landscape_h:"Where students turn today — and what's missing.",
 landscape_p:"Most tools handle one piece of the puzzle. Few connect the whole picture.",
 landscape_col_feature:"WHAT YOU NEED", landscape_col_counselor:"SCHOOL COUNSELOR", landscape_col_quiz:"CAREER QUIZ APPS", landscape_col_unisite:"UNIVERSITY WEBSITES", landscape_col_orbit:"ORBIT",
 landscape_row1:"Connects subjects, careers, degrees & universities in one view",
 landscape_row2:"Updates instantly as your subjects or interests change",
 landscape_row3:"Shows multiple possible futures, not a single verdict",
 landscape_row4:"Lets you test \u201cwhat if\u201d scenarios before committing",
 landscape_row5:"Available anytime — not limited to appointments",
 landscape_row6:"Compares specific universities side by side",
 landscape_note:"Based on the typical scope of each tool category — individual counselors and apps vary.",
 problem_label:"THE PROBLEM", problem_h:"You know what you study. But do you know what it could become?",
 evidence_label:"THE EVIDENCE", evidence_h:"The uncertainty is measurable.",
 matters_label:"WHY IT MATTERS", matters_h1:"The problem isn't a lack of possibilities.", matters_h2:"It's seeing how they connect.",
 solution_label:"THE SOLUTION", solution_h:"ORBIT connects the choices.",
 solution_p:"ORBIT connects what you study, what interests you and what you're good at with careers, degrees and universities — helping you explore multiple possible futures.",
 solution_flow_label:"THE SAME PATH, NOW CONNECTED",
 embed_label:"BEYOND ORBIT.COM", embed_h:"This doesn't have to be its own destination.",
 embed_p:"The matching engine behind ORBIT can be embedded directly into a university's own admissions site — a lightweight \u201cdoes this program fit me?\u201d widget that shows prospective applicants how their subjects and interests map onto that university's specific degrees, without ever leaving the page they're already on.",
 embed_tag1:"Embeddable widget", embed_tag2:"White-labelled to your site", embed_tag3:"Same engine, your branding", embed_tag4:"Drop-in API or iframe",
 ending_h:"DECISIONS, NOT DESTINY.", ending_p:"ORBIT doesn't predict your future. It helps you see more possible futures.",
 explore_constellation:"EXPLORE THE CONSTELLATION",
 saved_h:"Saved", saved_p_pre:"item(s) saved across your pathway universe.",
 careers_l:"Careers", degrees_l:"Degrees", universities_l:"Universities", remove:"Remove", no_saved_degrees:"No saved degrees.", no_saved_careers:"No saved careers yet.", no_saved_universities:"No saved universities yet.",
 compare_h:"Compare", compare_p_pre:"Comparing", compare_p_mid:"of 3 possible destinations.", add_to_compare:"Add to compare", remove_compare:"Remove",
 compare_empty:"Add up to 3 universities to compare them side by side.",
 pathways_h:"Pathways", pathways_p:"See how your subjects, careers, degrees and universities connect end to end.",
 pathways_demo_note:"Add universities to Compare to see them here — showing a sample pathway.",
 pathway_comparison_eyebrow:"PATHWAY COMPARISON", compare_pathways_h:"Compare pathways",
 compare_pathways_p_pre:"Visualizing", compare_pathways_p_post:"saved pathways across tuition, degree outcomes, and career alignment. Hover any chart for detail.",
 career_l:"CAREER",
 chart_tuition:"TUITION", chart_tuition_sub:"Estimated annual cost, normalized to USD. Sample data — not live verified.",
 chart_alignment:"CAREER ALIGNMENT", chart_alignment_sub:"How well each pathway's career fits your profile (0–99).",
 chart_outcomes:"DEGREE OUTCOMES", chart_outcomes_sub:"Number of distinct career pathways each degree unlocks.",
 chart_multiaxis:"MULTI-AXIS PROFILE", chart_multiaxis_sub:"Each pathway across five normalized dimensions (0–100).",
 career_unlocked_one:"career unlocked", career_unlocked_many:"careers unlocked",
 tuition_normalized:"Tuition normalized to USD for comparison", summary:"SUMMARY", pathway:"PATHWAY",
 profile_h:"Your signals", profile_p:"Edit what you study, what you're curious about, and what you're good at. Your matches recalculate instantly — no refresh needed.",
 theme_l:"THEME", language_l:"LANGUAGE", dark:"Dark", light:"Light",
 live_recalc:"LIVE RECALCULATION · TOP MATCHES", view_my_path:"View my path", rebuild_scratch:"Rebuild from scratch", reset_profile_btn:"Reset profile",
 saved_msg:"Saved", removed_msg:"Removed", compare_added:"Added to compare", compare_full:"Compare is full — remove one first", compare_removed:"Removed from compare",
 sample_demo:"SAMPLE DEMO DATA", sample_notlive:"SAMPLE DATA — NOT LIVE VERIFIED", latest_published:"LATEST PUBLISHED DATA · 2025",
 relevant_subjects:"RELEVANT SUBJECTS", relevant_interests:"RELEVANT INTERESTS", relevant_strengths:"RELEVANT STRENGTHS",
 back_to_careers:"Back to careers", compare_max:"Maximum 3 universities",
 admission_factors:"Admission factors", add_another:"Add another", slots_left:"slot(s) left", back_to_uni_explorer:"Back to university explorer", view_chart_comparison:"View chart comparison",
 build_step:"BUILD MY PATH · STEP", of4:"/ 04",
 search_ph:"Search careers, degrees or universities...",
 footer_tag:"One choice. Many connections. Multiple futures.",
 footer_mono:"DECISIONS, NOT DESTINY · SAMPLE DEMO DATA",
 footer_explore:"EXPLORE", footer_more:"MORE",
 footer_designathon:"Designed for RIT × TWE DesignAthon 2026",
 ai_fab_label:"Ask Orbit AI", ai_title:"Orbit AI", ai_subtitle:"Quick answers about Orbit", ai_close:"Close", ai_back:"← Ask something else",
 ai_disclaimer:"Preset answers, not a live chat.",
 tour_skip:"Skip tour", tour_back:"Back", tour_next:"Next", tour_finish:"Let's go →",
 tour_1_t:"Start with Build My Path", tour_1_d:"Tell ORBIT what you study, what you're curious about, and what you're good at — this is where your possibility space begins.",
 tour_2_t:"Explore Careers", tour_2_d:"Browse careers with a live match score based on your profile, and see why each one fits.",
 tour_3_t:"The Constellation", tour_3_d:"A living map of how careers connect. Click any node to re-center the universe around it.",
 tour_4_t:"Try What If", tour_4_d:"Change your profile hypothetically and watch the possibility space respond — instantly, without touching your real profile.",
 tour_5_t:"Find Universities", tour_5_d:"Explore real UAE and international destinations that match your path.",
 tour_6_t:"Your Profile", tour_6_d:"Edit your signals anytime — subjects, interests, strengths. Everything recalculates instantly.",
 tour_7_t:"Your Path", tour_7_d:"Once your profile is built, this is where it all comes together — your signals, top career matches, and a recommended pathway in one view.",
 tour_8_t:"Compare Universities", tour_8_d:"Add up to three universities and compare them side by side — tuition, scholarships, and admission factors.",
 tour_9_t:"Pathways", tour_9_d:"See your subjects, careers, degrees and universities charted end to end.",
 tour_10_t:"Why ORBIT", tour_10_d:"The problem ORBIT solves, and the research behind it.",
 tour_11_t:"Saved", tour_11_d:"Everything you bookmark along the way — careers, degrees, and universities — lives here.",
 tour_12_t:"Accessibility", tour_12_d:"Switch between English and Arabic, replay this tour anytime, or toggle dark/light mode — all built for accessibility.",
 tour_mobile_t:"Everything's in the menu", tour_mobile_d:"Tap here anytime to jump to Careers, Constellation, What If, Universities, and more."
},
ar:{
 nav_home:"الرئيسية",nav_mypath:"مساري",nav_careers:"المهن",nav_constellation:"الكوكبة",nav_universities:"الجامعات",nav_whatif:"ماذا لو",nav_why:"لماذا",nav_saved:"المحفوظات",nav_compare:"مقارنة",nav_pathways:"المسارات",nav_profile:"الملف الشخصي",nav_features:"الميزات",
 hero_label:"أوربت · محرك الاحتمالات",
 hero_l1:"انظر إلى أين",hero_l2:"يمكن أن تأخذك",hero_l3:"خياراتك.",
 hero_sub:"يربط أوربت موادك الدراسية واهتماماتك ونقاط قوتك بالمهن والتخصصات والجامعات التي قد تناسب مستقبلك.",
 cta_build:"ابنِ مساري", cta_explore_careers:"استكشف المهن",
 problem_home_h:"أنت تعرف ماذا تدرس. لكن هل تعرف ما يمكن أن يصبح عليه؟",
 problem_1_l:"المواد",problem_1_d:"ما تدرسه",problem_2_l:"المهن",problem_2_d:"ما يمكن أن يصبح عليه",problem_3_l:"التخصصات",problem_3_d:"كيف تصل إلى هناك",problem_4_l:"الجامعات",problem_4_d:"إلى أين تذهب",
 closing_label:"٠٥ — مستقبلات متعددة", closing_h1:"خيار واحد.", closing_h2:"روابط عديدة.", closing_h3:"مستقبلات متعددة.",
 possibility_h:"شاهد الاحتمالات تتغيّر.",
 possibility_p:"احذف مادة. أضف أخرى. تعيد الشبكة بأكملها التفكير في نفسها — المهن، التخصصات، الجامعات. قرارات، لا قدر محتوم.",
 cta_tryit:"جرّب ماذا لو",
 uni_label:"٠٤ — وجهات جامعية", uni_h:"أين يمكن أن يحطّ مسارك.", explore_all:"استكشف الكل",
 universe_h:"عالم من المهن، منظم حولك.",
 universe_p:"ترتبط كل مهنة بأخرى عبر مواد ومهارات وتخصصات مشتركة. استكشف العلاقات. اعثر على ما يناسبك.",
 open_constellation:"افتح الكوكبة",
 mypath_empty_h:"لم يُبنَ مسارك بعد.",
 mypath_empty_p:"أخبر أوربت بما تدرسه، وما يثير فضولك، وما تجيده — ثم شاهد احتمالاتك تظهر.",
 back:"رجوع", cont:"متابعة", generate:"إنشاء الاحتمالات",
 step_subjects_h:"ماذا تدرس؟", step_subjects_p:"اختر المواد التي تدرسها. كل مادة تصبح إشارة.",
 step_interests_h:"بماذا تشعر بالفضول؟", step_interests_p:"أضف المجالات التي تجذب انتباهك.",
 step_strengths_h:"ما الذي تجيده؟", step_strengths_p:"اختر نقاط القوة التي تشبهك أكثر.",
 step_futures_h:"ما نوع المستقبلات التي تهمك؟", step_futures_p:"اختياري — حدّد أنواع المسارات التي تريد رؤيتها.",
 selected:"مُختار", home_label:"الرئيسية", generating:"جارٍ إنشاء الاحتمالات", building_space:"جارٍ بناء فضاء احتمالاتك…",
 mypath_h:"مسارك", mypath_p:"استكشف الاحتمالات التي تنمو من ملفك الشخصي.", edit_profile:"تعديل الملف الشخصي",
 subjects_l:"المواد", interests_l:"الاهتمامات", strengths_l:"نقاط القوة", primary_pathway:"المسار الأساسي",
 top_matches:"أفضل تطابقات المهن", view_all:"عرض الكل", recommended_dest:"وجهات موصى بها", relevant_degree:"تخصص ذو صلة",
 careers_h:"المهن", careers_p:"استكشف إلى أين يمكن أن تقودك موادك واهتماماتك ونقاط قوتك.",
 explore:"استكشف", match:"تطابق", why_match:"لماذا يتطابق هذا",
 constellation_h:"الكوكبة", constellation_p:"مرّر للكشف عن العلاقات. اضغط على عقدة لإعادة توسيط الكون.",
 constellation_eyebrow:"كوكبة المهن",
 cl_label:"جارٍ رسم كونك", cl_sub:"نربط بين موادك واهتماماتك ونقاط قوتك…",
 connected_careers:"مهن مرتبطة", open_career:"افتح",
 universities_h:"الجامعات", universities_p:"استكشف الوجهات في عالم مسارك. تعكس درجات التطابق ملفك الشخصي.",
 search_uni:"ابحث عن الجامعات... (جرّب RIT، UWL، خليفة، إمبريال)",
 country_l:"الدولة", city_l:"المدينة", degree_l:"التخصص", budget_l:"الميزانية", all:"الكل", all_degrees:"كل التخصصات",
 whatif_h:"ماذا لو", whatif_p:"غيّر ملفك الشخصي افتراضيًا وشاهد فضاء الاحتمالات يستجيب — فورًا.",
 tab_subjects:"المواد", tab_interests:"الاهتمامات", tab_strengths:"نقاط القوة",
 current_subjects:"المواد الحالية", none_add:"لا شيء — أضف أدناه.", add_remove:"إضافة / إزالة",
 possibility_space:"فضاء الاحتمالات · أفضل المهن",
 pathway_gained:"مسار مكتسب", pathway_strengthened:"مسار معزّز", pathway_reduced:"مسار متراجع", no_change:"لا تغيير.",
 reset_profile:"إعادة الضبط إلى ملفي", hypothetical_note:"يبقى الملف الافتراضي منفصلاً عن ملفك الحقيقي. تعيد إعادة الضبط استعادته.",
 why_title:"المشكلة والحل",
 why_eyebrow:"لماذا أوربت", why_hero_h1:"قرارات،", why_hero_h2:"لا قدر محتوم.",
 why_hero_p:"لا يتنبأ أوربت بمستقبلك. بل يساعدك على رؤية الاحتمالات التي يمكن أن تفتحها خياراتك — وكيف يغيّر تغيير شيء واحد كل شيء.",
 future_options_l:"خيارات المستقبل", future_options_d:"ما يصبح ممكنًا",
 principle_label:"المبدأ",
 evidence_39:"من الطلاب في دول منظمة التعاون الاقتصادي والتنمية غير واضحين بشأن توقعاتهم المهنية.",
 evidence_21:"من الطلاب يمكن تصنيفهم كغير متوافقين مهنيًا — خططهم التعليمية وتوقعاتهم المهنية لا تتطابق.",
 evidence_gap:"عدم التوافق المهني بين الطلاب من الأرباع الاجتماعية والاقتصادية الأقل حظًا مقابل الأكثر حظًا — فجوة 23 نقطة مئوية.",
 src_39:"المصدر: منظمة التعاون الاقتصادي والتنمية — حالة الإعداد المهني للمراهقين عالميًا (20 مايو 2025)",
 src_21:"المصدر: منظمة التعاون الاقتصادي والتنمية — عدم اليقين المهني",
 src_gap:"المصدر: منظمة التعاون الاقتصادي والتنمية — مواجهة عدم المساواة الاجتماعية من خلال التوجيه المهني",
 misalignment_chart_title:"عدم التوافق المهني حسب الخلفية الاجتماعية والاقتصادية",
 misalignment_src:"المجموعة · النسبة · فجوة 23 نقطة مئوية بين المجموعتين · المصدر: منظمة التعاون الاقتصادي والتنمية. هذه نتائج بحثية عن مجموعات طلابية، وليست تنبؤًا بشأن أي فرد.",
 least_advantaged:"الأقل حظًا", most_advantaged:"الأكثر حظًا",
 landscape_label:"المشهد الحالي", landscape_h:"إلى أين يتجه الطلاب اليوم — وما الناقص؟",
 landscape_p:"معظم الأدوات تغطي جزءًا واحدًا فقط من الصورة. القليل منها يربط الصورة كاملة.",
 landscape_col_feature:"ما تحتاجه", landscape_col_counselor:"المرشد المدرسي", landscape_col_quiz:"تطبيقات اختبار المهن", landscape_col_unisite:"مواقع الجامعات", landscape_col_orbit:"أوربت",
 landscape_row1:"يربط المواد الدراسية والمهن والتخصصات والجامعات في مكان واحد",
 landscape_row2:"يتحدّث فورًا عند تغيّر موادك أو اهتماماتك",
 landscape_row3:"يعرض مستقبلات محتملة متعددة، لا نتيجة واحدة",
 landscape_row4:"يتيح لك تجربة سيناريوهات \u201cماذا لو\u201d قبل الالتزام",
 landscape_row5:"متاح في أي وقت — وليس محصورًا بمواعيد",
 landscape_row6:"يقارن جامعات محددة جنبًا إلى جنب",
 landscape_note:"استنادًا إلى النطاق المعتاد لكل فئة من الأدوات — قد تختلف التجربة حسب المرشد أو التطبيق.",
 problem_label:"المشكلة", problem_h:"أنت تعرف ماذا تدرس. لكن هل تعرف ما يمكن أن يصبح عليه؟",
 evidence_label:"الأدلة", evidence_h:"عدم اليقين قابل للقياس.",
 matters_label:"لماذا يهم هذا", matters_h1:"المشكلة ليست في نقص الاحتمالات.", matters_h2:"بل في رؤية كيفية ارتباطها.",
 solution_label:"الحل", solution_h:"أوربت يربط الخيارات.",
 solution_p:"يربط أوربت ما تدرسه وما يثير اهتمامك وما تجيده بالمهن والتخصصات والجامعات — ليساعدك على استكشاف مستقبلات محتملة متعددة.",
 solution_flow_label:"نفس المسار، لكنه الآن متصل",
 embed_label:"إلى ما هو أبعد من ORBIT.COM", embed_h:"لا يجب أن يكون وجهة قائمة بذاتها.",
 embed_p:"يمكن دمج محرك المطابقة الذي يشغّل أوربت مباشرة في موقع القبول الخاص بالجامعة — أداة خفيفة \u201cهل يناسبني هذا التخصص؟\u201d تُظهر للمتقدمين المحتملين كيف ترتبط موادهم واهتماماتهم بتخصصات تلك الجامعة تحديدًا، دون مغادرة الصفحة التي هم عليها بالفعل.",
 embed_tag1:"أداة قابلة للتضمين", embed_tag2:"بعلامة موقعكم الخاصة", embed_tag3:"نفس المحرك، بهويتكم", embed_tag4:"واجهة برمجية أو إطار iframe جاهز",
 ending_h:"قرارات، لا قدر محتوم.", ending_p:"لا يتنبأ أوربت بمستقبلك. بل يساعدك على رؤية مزيد من المستقبلات الممكنة.",
 explore_constellation:"استكشف الكوكبة",
 saved_h:"المحفوظات", saved_p_pre:"عنصر (عناصر) محفوظة عبر عالم مسارك.",
 careers_l:"المهن", degrees_l:"التخصصات", universities_l:"الجامعات", remove:"إزالة", no_saved_degrees:"لا توجد تخصصات محفوظة.", no_saved_careers:"لا توجد مهن محفوظة بعد.", no_saved_universities:"لا توجد جامعات محفوظة بعد.",
 compare_h:"مقارنة", compare_p_pre:"مقارنة", compare_p_mid:"من 3 وجهات ممكنة.", add_to_compare:"أضف للمقارنة", remove_compare:"إزالة",
 compare_empty:"أضف حتى 3 جامعات لمقارنتها جنبًا إلى جنب.",
 pathways_h:"المسارات", pathways_p:"شاهد كيف ترتبط موادك ومهنك وتخصصاتك وجامعاتك من البداية للنهاية.",
 pathways_demo_note:"أضف جامعات إلى المقارنة لرؤيتها هنا — يُعرض مسار تجريبي.",
 pathway_comparison_eyebrow:"مقارنة المسارات", compare_pathways_h:"قارن المسارات",
 compare_pathways_p_pre:"عرض", compare_pathways_p_post:"مسارات محفوظة عبر الرسوم الدراسية ومخرجات التخصص وتوافق المهنة. مرّر فوق أي رسم بياني للتفاصيل.",
 career_l:"المهنة",
 chart_tuition:"الرسوم الدراسية", chart_tuition_sub:"التكلفة السنوية التقديرية، موحدة بالدولار الأمريكي. بيانات تجريبية — غير مُتحقق منها مباشرة.",
 chart_alignment:"توافق المهنة", chart_alignment_sub:"مدى ملاءمة مهنة كل مسار لملفك الشخصي (٠–٩٩).",
 chart_outcomes:"مخرجات التخصص", chart_outcomes_sub:"عدد المسارات المهنية المتمايزة التي يفتحها كل تخصص.",
 chart_multiaxis:"الملف متعدد المحاور", chart_multiaxis_sub:"كل مسار عبر خمسة أبعاد موحدة (٠–١٠٠).",
 career_unlocked_one:"مهنة مفتوحة", career_unlocked_many:"مهن مفتوحة",
 tuition_normalized:"الرسوم موحدة بالدولار الأمريكي للمقارنة", summary:"ملخص", pathway:"المسار",
 profile_h:"إشاراتك", profile_p:"عدّل ما تدرسه، وما يثير فضولك، وما تجيده. تُحسب تطابقاتك فورًا — دون الحاجة لتحديث الصفحة.",
 theme_l:"المظهر", language_l:"اللغة", dark:"داكن", light:"فاتح",
 live_recalc:"إعادة حساب فورية · أفضل التطابقات", view_my_path:"عرض مساري", rebuild_scratch:"إعادة البناء من الصفر", reset_profile_btn:"إعادة ضبط الملف الشخصي",
 saved_msg:"تم الحفظ", removed_msg:"تمت الإزالة", compare_added:"أُضيف للمقارنة", compare_full:"المقارنة ممتلئة — أزل عنصرًا أولاً", compare_removed:"أُزيل من المقارنة",
 sample_demo:"بيانات تجريبية", sample_notlive:"بيانات تجريبية — غير مباشرة", latest_published:"آخر بيانات منشورة · ٢٠٢٥",
 relevant_subjects:"مواد ذات صلة", relevant_interests:"اهتمامات ذات صلة", relevant_strengths:"نقاط قوة ذات صلة",
 back_to_careers:"العودة إلى المهن", compare_max:"الحد الأقصى 3 جامعات",
 admission_factors:"عوامل القبول", add_another:"إضافة أخرى", slots_left:"مكان (أماكن) متبقية", back_to_uni_explorer:"العودة إلى مستكشف الجامعات", view_chart_comparison:"عرض مقارنة الرسوم البيانية",
 build_step:"ابنِ مساري · الخطوة", of4:"/ ٠٤",
 search_ph:"ابحث عن مهن أو تخصصات أو جامعات...",
 footer_tag:"خيار واحد. روابط عديدة. مستقبلات متعددة.",
 footer_mono:"قرارات، لا قدر محتوم · بيانات تجريبية",
 footer_explore:"استكشف", footer_more:"المزيد",
 footer_designathon:"صُمم لهاكاثون RIT × TWE DesignAthon 2026",
 tour_skip:"تخطي الجولة", tour_back:"رجوع", tour_next:"التالي", tour_finish:"لنبدأ ←",
 tour_1_t:"ابدأ ببناء مسارك", tour_1_d:"أخبر أوربت بما تدرسه، وما يثير فضولك، وما تجيده — هنا يبدأ فضاء احتمالاتك.",
 tour_2_t:"استكشف المهن", tour_2_d:"تصفح المهن مع درجة تطابق فورية بناءً على ملفك الشخصي، وشاهد لماذا يناسبك كل منها.",
 tour_3_t:"الكوكبة", tour_3_d:"خريطة حيّة لكيفية ارتباط المهن. اضغط على أي عقدة لإعادة توسيط الكون حولها.",
 tour_4_t:"جرّب ماذا لو", tour_4_d:"غيّر ملفك الشخصي افتراضيًا وشاهد فضاء الاحتمالات يستجيب — فورًا، دون المساس بملفك الحقيقي.",
 tour_5_t:"اعثر على الجامعات", tour_5_d:"استكشف وجهات حقيقية في الإمارات والعالم تناسب مسارك.",
 tour_6_t:"ملفك الشخصي", tour_6_d:"عدّل إشاراتك في أي وقت — المواد والاهتمامات ونقاط القوة. كل شيء يُحسب فورًا.",
 tour_7_t:"مسارك", tour_7_d:"بمجرد بناء ملفك الشخصي، هنا يجتمع كل شيء — إشاراتك، وأفضل تطابقات المهن، ومسار موصى به في نظرة واحدة.",
 tour_8_t:"قارن الجامعات", tour_8_d:"أضف حتى ثلاث جامعات وقارن بينها جنبًا إلى جنب — الرسوم الدراسية والمنح وعوامل القبول.",
 tour_9_t:"المسارات", tour_9_d:"شاهد موادك ومهنك وتخصصاتك وجامعاتك موضحة من البداية إلى النهاية.",
 tour_10_t:"لماذا أوربت", tour_10_d:"المشكلة التي يحلها أوربت، والأبحاث التي تستند إليها.",
 tour_11_t:"المحفوظات", tour_11_d:"كل ما تحفظه أثناء التصفح — المهن والتخصصات والجامعات — موجود هنا.",
 tour_12_t:"إمكانية الوصول", tour_12_d:"بدّل بين الإنجليزية والعربية، أعد تشغيل هذه الجولة في أي وقت، أو بدّل بين الوضع الداكن والفاتح — كلها مصممة لإمكانية الوصول.",
 tour_mobile_t:"كل شيء في القائمة", tour_mobile_d:"اضغط هنا في أي وقت للانتقال إلى المهن، الكوكبة، ماذا لو، الجامعات، والمزيد.",
 ai_fab_label:"اسأل أوربت الذكي", ai_title:"أوربت الذكي", ai_subtitle:"إجابات سريعة حول أوربت", ai_close:"إغلاق", ai_back:"← اسأل شيئًا آخر",
 ai_disclaimer:"إجابات معدة مسبقًا، وليست محادثة حية."
}
};

export const ORBIT_AI_QA = {
en:[
  { id:"what", q:"What is Orbit?", a:"Orbit connects what you study, what interests you, and what you're good at with careers, degrees, and universities — so you can see multiple possible futures instead of one path." },
  { id:"build", q:"How do I build my path?", a:"Tap \"Build My Path\" and pick your subjects, interests, and strengths across a few quick steps. Orbit instantly generates career matches and recommended destinations from your answers." },
  { id:"match", q:"How are matches calculated?", a:"Each career, degree, and university gets a match score from how closely its required subjects, skills, and interests overlap with your profile. Change your profile and matches recalculate instantly." },
  { id:"whatif", q:"What does \"What If\" do?", a:"What If lets you test a hypothetical profile — add or remove subjects and interests — and watch your possibility space shift, without touching your real saved profile." },
  { id:"privacy", q:"Is my data saved anywhere?", a:"Your profile and saved items are stored locally in your browser only. Nothing is uploaded — clearing your browser storage clears your Orbit data too." },
],
ar:[
  { id:"what", q:"ما هو أوربت؟", a:"يربط أوربت ما تدرسه، وما يثير اهتمامك، وما تجيده بالمهن والتخصصات والجامعات — لتتمكن من رؤية مستقبلات متعددة بدلاً من مسار واحد." },
  { id:"build", q:"كيف أبني مساري؟", a:"اضغط على \"ابنِ مساري\" واختر موادك واهتماماتك ونقاط قوتك عبر بضع خطوات سريعة. يُنشئ أوربت فورًا تطابقات مهنية ووجهات موصى بها بناءً على إجاباتك." },
  { id:"match", q:"كيف تُحسب درجات التطابق؟", a:"تحصل كل مهنة وتخصص وجامعة على درجة تطابق بناءً على مدى تداخل موادها ومهاراتها المطلوبة مع ملفك الشخصي. عند تغيير ملفك تُعاد حساب التطابقات فورًا." },
  { id:"whatif", q:"ما الذي تفعله ميزة \"ماذا لو\"؟", a:"تتيح لك ميزة \"ماذا لو\" تجربة ملف شخصي افتراضي — بإضافة أو حذف مواد واهتمامات — ومشاهدة فضاء احتمالاتك يتغيّر، دون المساس بملفك الحقيقي المحفوظ." },
  { id:"privacy", q:"هل تُحفظ بياناتي في مكان ما؟", a:"يُخزَّن ملفك الشخصي وعناصرك المحفوظة محليًا في متصفحك فقط. لا يُرفع شيء إلى الخادم — ومسح تخزين المتصفح يمسح بيانات أوربت أيضًا." },
]
};

export function universitiesForCareer(career){
  const ids = CATEGORY_UNI_MAP[career.category] || ["khalifa","rit"];
  return ids.map(id=>UNIVERSITIES.find(u=>u.id===id)).filter(Boolean);
}
